@resolve(MyService) throws error 'Can not read property of undefined' (#4)
* The property decorator must return a descriptor

* fix error TS6133

ERROR in ./src/internal/utils.ts
(74,9): error TS6133: 'bindingWhenOnSyntax' is declared but its value is never read.